name: Generar y Validar Dataset

on:
  push:
    branches:
      - main

jobs:
  generar-validar-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generar dataset de clientes
        run: python generar_dataset.py

      - name: Validar dataset
        run: python validar_dataset.py

      - name: Subir artefacto validado
        uses: actions/upload-artifact@v4
        with:
          name: dataset-clientes-validado
          path: Dataset_clientes_validado.csv
